In [8]:
#Standardization of data in python
#Method 1: Implementation in pandas [Z-Score]
# Importing the library
import pandas as pd
# Creating the data frame
details = {
'col1': [1, 3, 5, 7, 9],
'col2': [7, 4, 35, 14, 56]
    }
# creating a Dataframe object
df = pd.DataFrame(details)
# Z-Score using pandas
df['col1'] = (df['col1'] - df['col1'].mean()) / df['col1'].std()
df

       col1  col2
0 -1.264911     7
1 -0.632456     4
2  0.000000    35
3  0.632456    14
4  1.264911    56

In [9]:
#Method2: Using scipy.stats()
import pandas as pd
import scipy
from scipy import stats
# Creating the data frame
details = {
'col1': [1, 3, 5, 7, 9],
'col2': [7, 4, 35, 14, 56]
}
# creating a Dataframe object
df = pd.DataFrame(details)
# Z-Score using scipy
df['col2'] = stats.zscore(df['col2'])
df

   col1      col2
0     1 -0.824387
1     3 -0.977052
2     5  0.600480
3     7 -0.468171
4     9  1.669130

In [ ]:
# Standardizing continuous variables using z-score from scipy
from scipy.stats import zscore
continuous_vars = ['mpg', 'displacement', 'horsepower', 'weight', 'acceleration']
df[continuous_vars] = df[continuous_vars].apply(zscore)

In [5]:
# Method 3: Using sci-kit learn Standard scaler
# Importing the library
import pandas as pd
from sklearn.preprocessing import StandardScaler
# Creating the data frame
details = {
'col1': [1, 3, 5, 7, 9],
'col2': [7, 4, 35, 14, 56]
}
# creating a Dataframe object
df = pd.DataFrame(details)
# define standard scaler
scaler = StandardScaler()
# transform data
df = scaler.fit_transform(df)
df

array([[-1.41421356, -0.82438745],
       [-0.70710678, -0.97705179],
       [ 0.        ,  0.60047975],
       [ 0.70710678, -0.46817065],
       [ 1.41421356,  1.66913015]])